### ISSUE TITLE
write access

### ISSUE THREAD

**Issue by seadb** [grandcircusco/HF-Portal#27]
Can someone give me access to write to this repository?  I created some documentation which will be helpful for future development.  Also I can help with fixing bugs and potentially adding features.
This is Chelsea from Hacker Fellows Class of 2015
@Mierenga @thecodedad

**Comment by seadb** [comment]
this is Chelsea from Hacker Fellows class of 2015

**Comment by seadb** [comment]
@Mierenga

**Comment by Mierenga** [comment]
Ok sweet. @AndrewHigginbotham can you add Chelsea to this repo? I don't have admin rights.

**Comment by mtfurlan** [comment]
@AndrewHigginbotham Should just give @Mierenga admin, he's the one doing most of the stuff right now.

**Comment by AndrewHigginbotham** [comment]
Sorry guys I was away from the internet this weekend. Mike should have admin and Chelsea should be added
