### ISSUE TITLE
.gitignore rules

### ISSUE THREAD

**Issue by seadb** [grandcircusco/HF-Portal#4]
Please add .gitignore rules for the text editor that you use.  We already have vim and Sublime Text.

You can find a lot of common text editors here:
https://www.gitignore.io

Also if you see any technologies or frameworks you plan on using that I missed, please add .gitignore rules for those as well.  The less clutter in the git repository the better :+1: 

the .gitignore currently covers:
Sass
vim
Sublime Text
compressed files
logs/database files
Linux OS
Windows
Node.js

**Comment by kdunlap** [comment]
After a quick look at this file, it looks to be pretty inclusive for our needs at this point.
